dist: trusty
language: node_js
node_js:
  - "9"
  - "8"
  - "7"
  - "6"
env:
  - NODE_ENV=development
  - NODE_ENV=production
install: git clone --depth=1 https://github.com/doodadjs/travis_scripts.git ~/travis_scripts && chmod +x ~/travis_scripts/normal.sh
script: ~/travis_scripts/normal.sh